- name: Create Group 
  group:
    name: "{{ redmine.group.name }}"

- name: Create User
  user:
    name: "{{ redmine.user.name }}"
    create_home: true
    groups: 
      - "{{ redmine.group.name }}"
      - www-data
    comment: 'Redmine Management Account'
    expires: -1
    state: present
    shell: /bin/bash
    password:  "{{ redmine.user.password | password_hash('sha512', 'AZ') }}"
    update_password: on_create
    generate_ssh_key: true

# - name: Set-up Redmine Sudo Access 
#   copy:
#     dest: /etc/sudoers.d/redmine
#     content: "redmine ALL=(ALL) NOPASSWD:ALL"
#     validate: "/usr/sbin/visudo -cf %s"