
- name: Include Distro Specific Packages.
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Package Install Nginx Dependencies
  become: yes 
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ nginx_dependencies }}"

- name: Check If Key Should Be Downloaded 
  stat: 
    path: /usr/share/keyrings/nginx-archive-keyring.gpg
  register: key_downloaded 

- name: Import a key from a file
  become: yes
  shell: "curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor 
         | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null"
  args:
    executable: /bin/bash
  when: not key_downloaded.stat.exists

- name: Verify the key, using a fingerprint, before import
  shell: "gpg --dry-run --quiet --import --import-options  
          import-show /usr/share/keyrings/nginx-archive-keyring.gpg"
  register: nginx_key
  args:
    executable: /bin/bash

- debug:
    var: nginx_key

- name: Add specified repository into sources list using specified filename
  shell: 'echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] 
          http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" 
          | sudo tee /etc/apt/sources.list.d/nginx.list'
  args:
    executable: /bin/bash
  
- name: System Update && Upgrade
  become: yes
  package:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 

- name: Package Install Nginx Dependencies
  become: yes 
  package:
    name: nginx
    state: present
